-- MySQL Script generated by MySQL Workbench
-- 09/09/17 23:12:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dinamico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dinamico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dinamico` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema webDinamica
-- -----------------------------------------------------
USE `dinamico` ;

-- -----------------------------------------------------
-- Table `dinamico`.`sgd_campos_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_campos_documento` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC));


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_tipo_documento` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC));


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_facultad` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC));


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_categoria_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_categoria_documento` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC));


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_estudiante` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `total_creditos` INT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC));


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_documento` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `visado` INT NULL DEFAULT 0,
  `creditos` INT NULL,
  `sgd_categoria_idx` VARCHAR(45) NOT NULL,
  `sgd_estudiante_idx` INT NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC),
  INDEX `fk_sgd_documento_sgd_estudiante1_idx` (`sgd_estudiante_idx` ASC),
  CONSTRAINT `fk_sgd_documento_sgd_estudiante1`
    FOREIGN KEY (`sgd_estudiante_idx`)
    REFERENCES `dinamico`.`sgd_estudiante` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_posgrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_posgrado` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `sgd_facultad_idx` INT NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC),
  INDEX `fk_sgd_posgrado_sgd_facultad1_idx` (`sgd_facultad_idx` ASC),
  CONSTRAINT `fk_sgd_posgrado_sgd_facultad1`
    FOREIGN KEY (`sgd_facultad_idx`)
    REFERENCES `dinamico`.`sgd_facultad` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_posgrado_tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_posgrado_tipo_documento` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `sgd_tipo_documento_idx` INT NOT NULL,
  `sgd_posgrado_idx` INT NOT NULL,
  PRIMARY KEY (`idx`),
  INDEX `fk_sgd_posgrado_tipo_documento_sgd_tipo_documento1_idx` (`sgd_tipo_documento_idx` ASC),
  INDEX `fk_sgd_posgrado_tipo_documento_sgd_posgrado1_idx` (`sgd_posgrado_idx` ASC),
  CONSTRAINT `fk_sgd_posgrado_tipo_documento_sgd_tipo_documento1`
    FOREIGN KEY (`sgd_tipo_documento_idx`)
    REFERENCES `dinamico`.`sgd_tipo_documento` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgd_posgrado_tipo_documento_sgd_posgrado1`
    FOREIGN KEY (`sgd_posgrado_idx`)
    REFERENCES `dinamico`.`sgd_posgrado` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_datos_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_datos_documento` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `sgd_campos_documento_idx` INT NOT NULL,
  `sgd_documento_idx` INT NOT NULL,
  `sgd_posgrado_tipo_documento_idx` INT NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC),
  INDEX `fk_sgd_datos_documento_sgd_campos_documento1_idx` (`sgd_campos_documento_idx` ASC),
  INDEX `fk_sgd_datos_documento_sgd_documento1_idx` (`sgd_documento_idx` ASC),
  INDEX `fk_sgd_datos_documento_sgd_posgrado_tipo_documento1_idx` (`sgd_posgrado_tipo_documento_idx` ASC),
  CONSTRAINT `fk_sgd_datos_documento_sgd_campos_documento1`
    FOREIGN KEY (`sgd_campos_documento_idx`)
    REFERENCES `dinamico`.`sgd_campos_documento` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgd_datos_documento_sgd_documento1`
    FOREIGN KEY (`sgd_documento_idx`)
    REFERENCES `dinamico`.`sgd_documento` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgd_datos_documento_sgd_posgrado_tipo_documento1`
    FOREIGN KEY (`sgd_posgrado_tipo_documento_idx`)
    REFERENCES `dinamico`.`sgd_posgrado_tipo_documento` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dinamico`.`sgd_tipo_documento_campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinamico`.`sgd_tipo_documento_campo` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `valor_campo` VARCHAR(500) NOT NULL,
  `validacion` VARCHAR(60) NOT NULL,
  `sgd_posgrado_tipo_documento_idx` INT NOT NULL,
  `sgd_categoria_documento_idx` INT NOT NULL,
  `sgd_campos_documento_idx` INT NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC),
  INDEX `fk_sgd_tipo_documento_campo_sgd_categoria_documento1_idx` (`sgd_categoria_documento_idx` ASC),
  INDEX `fk_sgd_tipo_documento_campo_sgd_campos_documento1_idx` (`sgd_campos_documento_idx` ASC),
  CONSTRAINT `fk_sgd_tipo_documento_campo_sgd_categoria_documento1`
    FOREIGN KEY (`sgd_categoria_documento_idx`)
    REFERENCES `dinamico`.`sgd_categoria_documento` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgd_tipo_documento_campo_sgd_campos_documento1`
    FOREIGN KEY (`sgd_campos_documento_idx`)
    REFERENCES `dinamico`.`sgd_campos_documento` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
